### ISSUE TITLE
duplicate terms: Biological_process

### ISSUE THREAD

**Issue by linikujp** [BioAssayOntology/BAO#10]
There are duplicated Biological_process terms in BAO.
The following defines GO_0008150 is equivalent term of BAO_0000264.
We should directly use GO term instead of create another BAO equivalent term.

```
<!-- http://purl.obolibrary.org/obo/GO_0008150 -->

<rdf:Description rdf:about="&obo;GO_0008150">
    <owl:equivalentClass rdf:resource="http://www.bioassayontology.org/bao#BAO_0000264"/>
    <rdfs:subClassOf rdf:resource="http://www.bioassayontology.org/bao#BAO_0003114"/>
    <obo:IAO_0000412 rdf:resource="&obo;go.owl"/>
    <oboInOwl:inSubset rdf:resource="&obo;go#goslim_aspergillus"/>
    <oboInOwl:inSubset rdf:resource="&obo;go#goslim_candida"/>
    <oboInOwl:inSubset rdf:resource="&obo;go#goslim_generic"/>
    <oboInOwl:inSubset rdf:resource="&obo;go#goslim_metagenomics"/>
    <oboInOwl:inSubset rdf:resource="&obo;go#goslim_pir"/>
    <oboInOwl:inSubset rdf:resource="&obo;go#goslim_plant"/>
    <oboInOwl:inSubset rdf:resource="&obo;go#goslim_pombe"/>
    <oboInOwl:inSubset rdf:resource="&obo;go#goslim_yeast"/>
    <oboInOwl:inSubset rdf:resource="&obo;go#gosubset_prok"/>
</rdf:Description>
```

**Comment by linikujp** [comment]
There are a lot of such issues:

For example, Cellular quality has two ids: PATO_0001396 and BAO_0120000

**Comment by sschurer** [comment]
Defined as identical for the purpose of incorporation of external modules.
We need a BAO structure and then map these formally to the external
ontologies. We need to control the internal BAO structure. Similar one
needs axioms to map BAO terms to BFO; i.e. we want to be able to plug in or
plug out BFO. Stephan

**Comment by linikujp** [comment]
1. This may create an obstacle for end user. 
2 . The equivalent class will add all the axioms of both terms together. It might cause some reasoning problems later.

We will watch this issue....

In order to to opt-in and opt-out BFO or any other modules, there maybe other choices.
We will test.

**Comment by sschurer** [comment]
That's right, but equivalent means equivalent; we are essentially accepting
this. we have to review this. Let's see if we can do that better. I copy
Hande and Sam. Sam did this originally from the computer science
perspective. Stephan

**Comment by linikujp** [comment]
Instead of using equivalent classes, another option is to use SKOS system. 
http://www.w3.org/2004/02/skos/vocabs
The skos:exactMatch should work fine in BAO's situation.
