### ISSUE TITLE
add external IDs

### ISSUE THREAD

**Issue by chung88** [BioAssayOntology/BAO#102]
the list has 3 records

**Comment by JoanGlennyPescov** [comment]
yes it does. but we have used these 3 external sources before (in BAO)

**Comment by chung88** [comment]
ERO will not be used, the last update is from 2013

module	id
CLO	http://purl.obolibrary.org/obo/CLO_0002172
NCBITaxon	http://purl.obolibrary.org/obo/NCBITaxon_9541
