### ISSUE TITLE
kp endpoint

### ISSUE THREAD

**Issue by Scientist328455** [BioAssayOntology/BAO#103]
Can you add a new assay endpoint 'kp' to the Assay Result Component > Endpoints > ratio endpoint?

**Preferred Name:** kp
**Definitions:** Kp values are defined as the ratio of total concentration of compound in the tissue to total concentration of compound in the plasma at steady state.
**subClassOf:** ratio endpoint (BAO_0080042)
**Justification:** kp is a common pharmacology endpoint

**Comment by Scientist328455** [comment]
Thank you. w.r.t. to Stephan's comment I'm not wild about having the 'Partition Coefficient' class. In my mind this creates hierarchy issues with kp, octanol-water partition coefficients P, logP, and logD. Because P, logP, and logD only depend on the compound I think of them as physical properties. The kp depends on the compound and the tissue so I think of it as a different kind of endpoint.

One possibility would be to remove the partition coefficient class, but I will leave that for you to discuss.

**Comment by sschurer** [comment]
Correct. That is one of the issues we need to optimize in the endpoint hierarchy. But we can still add Kp, because a change in the hierarchy will not cause a problem with its URI, etc.

**Comment by chung88** [comment]
see comment in [bao git-101](https://github.com/BioAssayOntology/BAO/issues/101)

**Comment by chung88** [comment]
<img width="1375" alt="Screen Shot 2023-10-10 at 7 39 15 AM" src="https://github.com/BioAssayOntology/BAO/assets/3586358/e64fd023-08d1-4d40-a8fe-c0f522833eda">


https://bioportal.bioontology.org/ontologies/BAO/?p=classes&conceptid=http%3A%2F%2Fwww.bioassayontology.org%2Fbao%23BAO_0080049&jump_to_nav=true
