### ISSUE TITLE
Pertubagen must link to bioassay

### ISSUE THREAD

**Issue by linikujp** [BioAssayOntology/BAO#11]
Pertubagen is an important concept in bioassay. 
Pertubagen is a role in BAO, which can be beared by multiple entities.
According to this paper (http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4086130/): perturbations are chemical reagents including drugs, ligands and other small molecules applied at different time points and doses.
Above indicates that drug, ligand and small molecules can be pertubagen.

Suggestion: To create a has_pertubagen which directly link assay to any entities serves as a pertubagen.

**Comment by sschurer** [comment]
Makes sense. We may have that in BAO. Probably links to measure group to accommodate multiplexed assays. Stephan

**Comment by sschurer** [comment]
We may want to rename perturbagen into perturbagen role to make that clear.
We could then define a material entity perturbagen that is a screened
entity with the role perturbagen role
