### ISSUE TITLE
Typo in BAO ontology description

### ISSUE THREAD

**Issue by JKChang2015** [BioAssayOntology/BAO#12]
In the following entry: http://aber-owl.net/ontology/ENM#!http%3A%2F%2Fwww.bioassayontology.org%2Fbao%23BAO_0000015
there is a typo: "a set of instructions, methodology, operations, required reagents, instruments to carrie out experiments".

**Comment by linikujp** [comment]
Thanks! We will correct it.

**Comment by egonw** [comment]
This bug is filed in the ENM repos as: https://github.com/enanomapper/ontologies/issues/35

**Comment by linikujp** [comment]
This bug is corrected

**Comment by sschurer** [comment]
Thank you Asiyah! Stephan
