### ISSUE TITLE
What is Kinactivation?

### ISSUE THREAD

**Issue by Scientist328455** [BioAssayOntology/BAO#121]
Can you add a definition Kinactivation? https://bioportal.bioontology.org/ontologies/BAO/?p=classes&conceptid=http%3A%2F%2Fwww.bioassayontology.org%2Fbao%23BAO_0001258

**Comment by chung88** [comment]
<img width="1633" alt="Screen Shot 2024-02-21 at 9 40 12 PM" src="https://github.com/BioAssayOntology/BAO/assets/3586358/bdc229fe-ccc3-49df-85cf-a1be2dc305ff">

**Comment by chung88** [comment]
BioPortal "Definitions" property parse searches "rdfs:comment", "skos:definition" and "obo:IAO_0000115"
