### ISSUE TITLE
Add kobs

### ISSUE THREAD

**Issue by Scientist328455** [BioAssayOntology/BAO#122]
Can you add a kobs endpoint? 

**Name**: kobs
**Description**: Inactivation rate constant at a specific test concentration. It has units of 1/min. 
**Subclass of**: enzyme kinetic constant (BAO_0000487)

The Time Dependent Inhibition in Human Liver Microsomes, measured by kobs, is described for 50 drugs in this paper: https://dmd.aspetjournals.org/content/49/6/442.long

**Comment by chung88** [comment]
Dear @Scientist328455, can you please email me directly  "c dot chung at miami dot edu"? - thanks

**Comment by chung88** [comment]
<img width="943" alt="Screen Shot 2024-02-21 at 2 40 07 PM" src="https://github.com/BioAssayOntology/BAO/assets/3586358/63647b14-bb85-4a11-9de7-8c596cb69076">

**Comment by chung88** [comment]
URL provided returns error code 502
<img width="861" alt="Screen Shot 2024-02-21 at 2 44 46 PM" src="https://github.com/BioAssayOntology/BAO/assets/3586358/a45359a4-aaee-487f-b6f1-03ad073a82b7">

**Comment by Scientist328455** [comment]
Maybe it will work from the DOI:
https://doi.org/10.1124/dmd.121.000356
