### ISSUE TITLE
BioPortal 	12/16/2016 shows 2.0 

### ISSUE THREAD

**Issue by chung88** [BioAssayOntology/BAO#16]
BioPortal submission table shows:
	12/16/2016 version 2.0 
BioPortal picks up the version from the *.owl from:
http://www.bioassayontology.org/bao/bao_complete.owl
section:
       <owl:versionInfo>2.0</owl:versionInfo>
        <rdfs:comment>Created by:
Hande KÃ¼Ã§Ã¼k McGinty, Janice Kranz, Joseph Ostrow, Alex Clark, Yu Lin, Saminda Abeyruwan, Uma Vempati, Kunie Sakurai, Vance Lemmon, Ubbo Visser,  Stephan Schurer*</rdfs:comment>
        <rdfs:comment>svn:  2986</rdfs:comment>
        <rdfs:comment>Release date: November 18, 2014</rdfs:comment>

**Comment by handemcginty** [comment]
I think we fixed this.
