### ISSUE TITLE
Possible Bioportal issue?

### ISSUE THREAD

**Issue by mkoatwork** [BioAssayOntology/BAO#20]
Don't know if this is interesting for you, but the Bioportal displays the term "ATP quantitation using luciferase" in class "assay desig method" as well as in subclass "viability measurement method" - "ATP quantitaion". 
![grafik](https://user-images.githubusercontent.com/19821604/27956749-766ba7c8-631b-11e7-9f8d-f9a5667171c3.png)
I don't know why this happens. In the owl file bao_vocabulary_method.owl the term is define only for subclass "ATP quantitation"
Ontology lookup service displays the correct hierarchy.

**Comment by chung88** [comment]
Thank you, we can report the display issue to BioPortal.

On Jul 7, 2017, at 7:56 AM, mkoatwork <notifications@github.com<mailto:notifications@github.com>> wrote:


Don't know if this is interesting for you, but the Bioportal displays the term "ATP quantitation using luciferase" in class "assay desig method" as well as in subclass "viability measurement method" - "ATP quantitaion".
[grafik]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_19821604_27956749-2D766ba7c8-2D631b-2D11e7-2D9f8d-2Df9a5667171c3.png&d=DwMCaQ&c=y2w-uYmhgFWijp_IQN0DhA&r=tfVNj79zKKEimhm8w8olzHqACL-jHGlkbH4tAX6Zz98&m=jG0SKtoVAFKMjzq_5THH4xP9m43IXyGzrhQTlUoDQ-M&s=I2aCP9mS8uavOyvzyPmpsFZR3eN81EXJahHVzRcHc1c&e=>
I don't know why this happens. In the owl file bao_vocabulary_method.owl the term is define only for subclass "ATP quantitation"
Ontology lookup service displays the correct hierarchy.

**Comment by chung88** [comment]
From: support@bioontology.org <support@bioontology.org>
Sent: Friday, July 7, 2017 11:33 AM
Subject: [BioPortal] Feedback
Location: http%3A%2F%2Fbioportal.bioontology.org%2F

Feedback:
Possible Bioportal issue? https://github.com/BioAssayOntology/BAO/issues/20
Bioportal displays the term "ATP quantitation using luciferase" in class "assay desig method" as well as in subclass "viability measurement method" - "ATP quantitation".
In the owl file bao_vocabulary_method.owl the term is define only for subclass "ATP quantitation" 
Ontology lookup service displays the correct hierarchy.
