### ISSUE TITLE
circular dependency makes it impossible to load the ontology with OWLAPI 5

### ISSUE THREAD

**Issue by egonw** [BioAssayOntology/BAO#24]
I ran into this problem after upgrading the eNanoMapper `Slimmer` tool to OWLAPI 5.1.1 with loading of `http://www.bioassayontology.org/bao/bao_complete.owl`, but can confirm it with the latest Protege too. The phenotype is this error message (for both):

```
Ontology already exists. OntologyID(OntologyIRI(<http://www.bioassayontology.org/bao/bao_complete.owl>) VersionIRI(<http://www.bioassayontology.org/bao/bao_complete.owl>))
```

I ran into this problem for the `CHEMINF` ontology too, an discovered a circular dependency. When I remove that circular dep, then both tools were able to load the ontology. For `BAO` I notice the same problem, and suspect this to be the reason here too, why the two tools cannot load ontology: `bao_complete.owl` imports `bao_core.owl` and `bao-core.owl` imports `bao_complete.owl`:

```xml
<owl:Ontology rdf:about="http://www.bioassayontology.org/bao/bao_core.owl">
  <owl:versionIRI rdf:resource="http://www.bioassayontology.org/bao/bao_core.owl"/>
  <owl:imports rdf:resource="http://www.bioassayontology.org/bao/bao_external.owl"/>
  <owl:imports rdf:resource="http://www.bioassayontology.org/bao/bao_complete.owl"/>
```

**Comment by sschurer** [comment]
Hi Egon, we will look into that. Were you able to identify the exact
circular dependency?

**Comment by whinis** [comment]
I have fixed the issue internally, Was a bug in the automated generation so should be fixed in the next release

**Comment by egonw** [comment]
@sschurer, yes, the snippet was given in the report. @whinis, thanks!

**Comment by whinis** [comment]
@egonw I just pushed a fixed core.owl file that should hopefully fix this issue until the next release
