### ISSUE TITLE
Invalid character in bao_complete.owl

### ISSUE THREAD

**Issue by stevevestal** [BioAssayOntology/BAO#47]
When I fetched subject ontology from http://www.bioassayontology.org/bao/bao_complete.owl and tried loading it using Apache Jena, I got a RiotException that the file had an invalid format:

[line: 248, col: 10] {E202} Expecting XML start or end element(s). String data "\\" not allowed. Maybe a striping error.

At line 248, there is a stray "\\" in the file.  Deleting this allowed the file to load.

**Comment by whinis** [comment]
Thank you for this, will be updated soon

**Comment by stevevestal** [comment]
I also get a RiotException for bao_vocabulary_role.owl and bao_clo_import.owl that characters are not in UTF-8 unicode format.  Loading a local copy and forcing a save in the Eclipse XML editor to write in standard UTF-8 will work for bao_vocabulary_role but not for bao_clo_import.  Apache Jena still finds a number of characters it does not like in that one.

**Comment by whinis** [comment]
Thank you, I typically load this in Protege and never seen any reports of issues. I will load in Jena and see what it tells me.

**Comment by whinis** [comment]
I have uploaded a new version and it seems to validate with Jena that I downloaded as much as it can (did not test imports as I don't entirely control the ontologies). Can you confirm ?
