### ISSUE TITLE
Missing Import for BAO_NCIT_import.owl

### ISSUE THREAD

**Issue by markmcdowall** [BioAssayOntology/BAO#48]
Hi,

I tried loading the BAO owl file using ROBOT, but when I import the vocab via the URL http://purl.obolibrary.org/obo/agro.owl it is unable to find one of the imported OWL files - http://www.bioassayontology.org/bao/external/BAO_NCIT_import.owl

I had a look at this page and I get an HTTP 404 error.

Cheers,

Mark

**Comment by whinis** [comment]
Sorry that should be working now

**Comment by markmcdowall** [comment]
Cheers, looks to be working again.
