### ISSUE TITLE
Incorporate Study Term

### ISSUE THREAD

**Issue by sschurer** [BioAssayOntology/BAO#56]
A Study is a collection of two or more Experiments or Studies where the summary is drawn from the assembly of information that provides more knowledge than the Experiments do individually.”

In other words, Studies group related Experiments and Studies together. Note in particular that for a Translational & In vivo Study, this means:
·         A (completed) Study cannot contain only a single Experiment.
·         Results can be associated with either an Experiment or a Study.
·         Studies can contain other Studies in a hierarchy. 

 
***The way I developed a data contact is Study à [1:n (One to Many)] Experiment  à [1:n (One to Many)] Assay……i.e. .Study cannot have a direct relationship to Assay without Experiment.

Consider ISA structure: Investigation, Study, Assay: https://isa-tools.org

**Comment by chung88** [comment]
Duplicate issue refer to:
[baogit-64](https://github.com/BioAssayOntology/BAO/issues/64)
