### ISSUE TITLE
add new terms

### ISSUE THREAD

**Issue by chung88** [BioAssayOntology/BAO#60]
| new BAO hierarchy | parent ID | parent label | new label | definition |
|---|---|---|---|---|
 |assay bioassay component>study | BAO_0003112 | assay bioassay component | study |  |
 |assay bioassay component>disease model | BAO_0003112 | assay bioassay component | disease model |  |

@chung88:  do you have a definition for study and disease model?
@JoanGlennyPescov No definition was included for either on the sheet that I could put. Is this something that can be added later?

**Comment by chung88** [comment]
module:  vocabulary_assay
range:  10000  to 19999
assign BAO_0010278; BAO_0010279
verify:  https://ontobee.org/ontology/BAO?iri=http%3A%2F%2Fwww.bioassayontology.org%2Fbao%23BAO_0010278 
Term Not Found
git script tools/BAO_DB/sql_scripts/addNewTerm.sql

ready for QA/QC

**Comment by chung88** [comment]
Nicolette:  Move BAO_0010279 under BAO_0003114:   <img width="1022" alt="Screen Shot 2023-02-20 at 11 29 17 AM" src="https://user-images.githubusercontent.com/3586358/220159328-70a8830f-edf5-4451-b309-3c0596466548.png">

**Comment by chung88** [comment]
[02/21/2023 slack 3:08]  Nicolette and @JoanGlennyPescov  agreed on definitions
they can be used now

[BAO_new_terms.xlsx](https://github.com/BioAssayOntology/BAO/files/10804330/BAO_new_terms.xlsx)

**Comment by JoanGlennyPescov** [comment]
add new google sheet with disease under assay biology component

**Comment by JoanGlennyPescov** [comment]
> Nicolette: Move BAO_0010279 under BAO_0003114: <img alt="Screen Shot 2023-02-20 at 11 29 17 AM" width="1022" src="https://user-images.githubusercontent.com/3586358/220159328-70a8830f-edf5-4451-b309-3c0596466548.png">

disease model label was assigned parent "assay biology component"[https://docs.google.com/spreadsheets/d/15BXyuD29ywbivI3QQe9h-BcmQJk50ror/edit#gid=683968424](url)

**Comment by JoanGlennyPescov** [comment]
In "BAO new terms version 3" the "study" label was changed to "pre-clinical study". Also, definitions were added to both "disease model" and "pre-clinical study". Changes are noted in "BAO new terms version 3" link[https://docs.google.com/spreadsheets/d/1CgTUeisg_Kuo2pce34VMNd4v1TnIB2c2/edit#gid=1138483307](url)

**Comment by chung88** [comment]
Complete
Release Notes for BAO version 2.7.5
