### ISSUE TITLE
Move terms

### ISSUE THREAD

**Issue by chung88** [BioAssayOntology/BAO#61]
The spreadsheet has 65 records to move.
[BAO_change_parent.xlsx](https://github.com/BioAssayOntology/BAO/files/10769457/BAO_change_parent.xlsx)

**Comment by chung88** [comment]
Ready for QA/QC review

**Comment by chung88** [comment]
<img width="350" alt="Screen Shot 2023-02-20 at 11 42 15 AM" src="https://user-images.githubusercontent.com/3586358/220161868-c9a34577-0445-4f41-bec3-f70935e4cf96.png">

**Comment by chung88** [comment]
Spreadsheet input typo:
<img width="1611" alt="Screen Shot 2023-02-20 at 12 03 23 PM" src="https://user-images.githubusercontent.com/3586358/220165962-e7a5bf02-6b30-48ff-a413-6f194534b4e8.png">

**Comment by chung88** [comment]
@JoanGlennyPescov @sschurer   discuss term:  drug interaction assay (BAO_0002188)

**Comment by JoanGlennyPescov** [comment]
> 
In my notes, we were just changing its parent to "bioassay"
we are not doing anything with the term at all.

but I just asked Nicolette what is wrong with the label itself and it appears to be kind of vague


Nicolette said we can keep the label 'drug interaction assay' as it is for now. That this should not hold up the current release. A change for that label should go into the next release.

**Comment by JoanGlennyPescov** [comment]
"BAO change parent version 2"
https://drive.google.com/drive/u/1/folders/1tXxlwLPsY_YEgEGmPF1aZKQCgvXJ21vb

changes are:
- pharmacometrics term is deprecated

- the parent of "portal vein study" is "preclinical study" and not "pre-clinical study"

- Dr. Schurer wanted for me to see how "kinome activity assay" the parent was in 2.6 or before Primary Pharmacodynamics was introduced to DB. This label was introduced with Primary Pharmacodynamics in BAO 2.7.2 (this is just an observation, no changes made)

**Comment by chung88** [comment]
deprecation of pharmacometrics will be on the milestone for BAO v2.7.6

**Comment by JoanGlennyPescov** [comment]
"BAO change parent version 2"
https://drive.google.com/drive/u/1/folders/1tXxlwLPsY_YEgEGmPF1aZKQCgvXJ21vb

has been updated to not include pharmacometrics

**Comment by chung88** [comment]
Complete
Release Notes for BAO version 2.7.5
