### ISSUE TITLE
Add New Enpoint: 'Electrical Current Density'

### ISSUE THREAD

**Issue by Scientist328455** [BioAssayOntology/BAO#62]
Can you add a new assay endpoint 'Electrical Current Density' to the Assay Result Component > Endpoints?

I think the sub class would probably be new, something like: 'electrical'.  The endpoint details would be:

Preferred Name: Electrical Current Density
Definitions: Electrical Current Density is a measure of the density of flow of electric charge; it is the electric current per unit area of cross section. Electric current density is a vector-valued quantity.
subClassOf: electrical
Justification: This is in the QUDT (https://qudt.org/vocab/quantitykind/ElectricCurrentDensity); it is an endpoint for assays that measure ion transport https://en.wikipedia.org/wiki/Ussing_chamber

**Comment by exocyclic** [comment]
We should be able to do this. Patch-clamp electrophysiology assays do use electrical current density as endpoint measurement. We already have 'patch clamp' under physical detection method [under 'microelectrode measurement']. Maybe:
assay result component > endpoint > electrical endpoint > electrical current density ?? If Stephan agrees to this?

**Comment by Scientist328455** [comment]
Thanks for the update. Putting it in assay result component > endpoint > electrical endpoint > electrical current density sounds good to me. Will you let me know when the endpoint is added? Thanks.

**Comment by chung88** [comment]
Please provide information to replace =  [?]. 

**Proposed BAO label:  _electrical current density_**

**Proposed BAO definition**: [?]
Please provide a definition to "electrical current density" and the source of the definition?

**Proposed BAO hierarchy**: [?]
Please consider the definition for the BAO module.  My guess is that electric current density is the amount of electric current flowing through a given area or surface, if the unit of measurement is amperes per square meter or centimeter.  
a)  Is it assay method component?
'patch clamp' is under physical detection method.
assay method component>physical detection method>electrical sensor>patch clamp
assay method component>[?]
b)  Is it assay endpoint component?
assay endpoint component>[?]

**Parent BAO ID**:  [?]
**Parent BAO label**:  [?] 
The parent BAO label is verification to the parent BAO ID.

**Comment by Scientist328455** [comment]
**Proposed BAO label:** electrical current density

**Proposed BAO definition:** Electrical Current Density is a measure of the density of flow of electric charge; it is the electric current per unit area of cross section. Electric current density is a vector-valued quantity. https://qudt.org/vocab/quantitykind/ElectricCurrentDensity

**Proposed BAO hierarchy:** assay endpoint component > endpoint > electrical endpoint > electrical current density

**a) Is it assay method component?** This is an assay endpoint component
**b) Is it assay endpoint component?** Yes

Parent BAO ID: [You tell me?]
Parent BAO label: [You tell me?]
The parent BAO label is verification to the parent BAO ID.

**Comment by JoanGlennyPescov** [comment]
This the BAO parent and hierarchy it can be in. Such change will need to be approved by Dr. Schurer.
Let me know if you guys agree.

assay endpoint component (BAO_0003115) > result (BAO_0000179) > physical property endpoint (BAO_0002128) > electrical current density


Proposed BAO definition: Electrical Current Density is a measure of the density of flow of electric charge; it is the electric current per unit area of cross section. Electric current density is a vector-valued quantity. https://qudt.org/vocab/quantitykind/ElectricCurrentDensity

**Comment by Scientist328455** [comment]
I do not think the current density should be a sub class of physical property endpoint. The physical property endpoint is defined as "A measurement of an intrinsic property of a molecular entity." The current density is an endpoint for an assay that measures ion transport like an ussing assay (https://en.wikipedia.org/wiki/Ussing_chamber). I think a new category 'electrical endpoint' should be added to the assay endpoint component. 

assay endpoint component > endpoint > electrical endpoint > electrical current density

**Comment by JoanGlennyPescov** [comment]
assay endpoint component (BAO_0003115) > endpoint (BAO_0000179) > electrical endpoint (New ID) > electrical current density (New ID)

^^
I agree, this is more appropriate.

**Comment by Scientist328455** [comment]
Do you know when the electrical current density endpoint will be added to the ontology? I thought maybe it would be in 2.8.2 but I see that 2.8.2 is released and I cannot find it. Thanks.

**Comment by chung88** [comment]
BAO label:  electrical endpoint
BAO ID:  BAO_0080046
BAO label:  electrical current density
BAO ID:  BAO_0080047
![image](https://github.com/BioAssayOntology/BAO/assets/3586358/df89adfa-984c-41f8-89ab-af4d5b144f52)

Note:  Protege will display the label results and BioPortal display the label endpoint, both labels exist in BAO ID http://www.bioassayontology.org/bao#BAO_0000179
