### ISSUE TITLE
deprecate BAO classes and remove external terms

### ISSUE THREAD

**Issue by chung88** [BioAssayOntology/BAO#63]
[BAO_remove_parent.xlsx](https://github.com/BioAssayOntology/BAO/files/10777417/BAO_remove_parent.xlsx)
[BAO_remove_children.xlsx](https://github.com/BioAssayOntology/BAO/files/10777418/BAO_remove_children.xlsx)

**Comment by chung88** [comment]
@JoanGlennyPescov 
Can you check where should the following belong to?
id | label | parent id|
-- | -- | -- |
BAO_0010235 | rodent excretion in urine | BAO_0010234 |
BAO_0010236 | rodent IV clearance | BAO_0010234 |
BAO_0010237 | rodent IV half-life | BAO_0010234 |
BAO_0010238 | rodent oral bioavailability | BAO_0010234 |
BAO_0010239 | rodent oral half-life | BAO_0010234 |
BAO_0010240 | rodent Vdss | BAO_0010234 |
BAO_0010230 | non-rodent IV half-life | BAO_0010227 |
BAO_0010231 | non-rodent oral bioavailability | BAO_0010227 |
BAO_0010232 | non-rodent oral half-life | BAO_0010227 |
BAO_0010233 | non-rodent Vdss | BAO_0010227 |
BAO_0010228 | non-rodent excretion in urine | BAO_0010227 |
BAO_0010229 | non-rodent IV clearance | BAO_0010227 |

**Comment by JoanGlennyPescov** [comment]
change release name to "deprecate"

**Comment by JoanGlennyPescov** [comment]
change release name to "deprecate and remove external terms"

**Comment by chung88** [comment]
If a BAO ID under an external ID is deprecated, the BAO ID transverse to the upper, otherwise it will fall under root.  For example:
BAO_0000015
|->BAO_0002183
|-|->NCIT_C79364 deleted from BAO
|-|-|->BAO_0010256 deprecated

**Comment by chung88** [comment]
Complete
Release Notes for BAO version 2.7.5
