### ISSUE TITLE
new SEED classes

### ISSUE THREAD

**Issue by chung88** [BioAssayOntology/BAO#67]
Relationships depend on this new classes:
[file](https://docs.google.com/spreadsheets/d/1ilE8Y2KIlxwXKNTjvYagOyfLozvFs1_8ETlpmPK-CPM/edit#gid=1585539669)

**Comment by chung88** [comment]
@JoanGlennyPescov the snippet above has been copy and pasted into: https://github.com/BioAssayOntology/BAO/wiki/Cardinality

**Comment by sschurer** [comment]
More precisely:
https://ontology101tutorial.readthedocs.io/en/latest/OWL_ClassRestrictions.html#:~:text=Quantifier%20restrictions%20are%20further%20categorized,members%20of%20a%20specified%20class.

Quantifier restrictions are further categorized into two types, the existential and the universal restriction.

  *   Existential restrictions describe classes of individuals that participate in at least one relationship along a specified property to individuals that are members of a specified class. For example, the class of individuals that have at least one ( some ) ‘part of’ relationship to members of the ‘Chromosome clas. In Protégé, the keyword ‘ some’ is used to denote existential restrictions.
  *   Universal restrictions describe classes of individuals that for a given property only have relationships along this property to individuals that are members of a specified class. For example, we can say a cellular component is capable of many functions using the existential quantifier, however, OWL semantics assume that there could be more. We can use the universal quantifier to add closure to the existential. That is, we can assert that a cellular component is capable of these function, and is only capable of those functions and no other. Another example is that the process of hair growth is found only in instances of the class Mammalia. In Protégé the keyword ‘only’ is used.

Also see Description logic existential or universal restrictions: https://en.wikipedia.org/wiki/Description_logic


______________________________________________________

Stephan Schürer, PhD
Professor, Department of Pharmacology, Miller School of Medicine, University of Miami
Associate Director of Data Science, Sylvester Comprehensive Cancer Center, Miller School of Medicine, University of Miami
Director of Digital Drug Discovery, Institute for Data Science & Computing, University of Miami
1600 NW 10th Avenue, RMSB 6112B, Miami, FL 33136
http://schurerlab.org/
https://idsc.miami.edu/research/digital-health/drug-discovery/
http://bd2k-lincs.org
https://druggablegenome.net/
email: ***@***.******@***.***>
phone: +1-305-243-6552 (office)

On Mar 13, 2023, at 3:20 PM, Joan C. Glenny Pescov ***@***.******@***.***>> wrote:

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.


"Cardinality restrictions in OWL allow us to say how many distinct values a property can have for any given subject.
Other restrictions tell us about the classes of which those values can or must be members". - ScienceDirect

some = many subjects can have a type of property
only = only this subject can have this property

The equivalent class IC50 specifies "has mode of action" only "inhibition". "Only" here denotes universal quantification, describing all the individuals whose "has mode of action" relationships refer to members of the class inhibition; or conversely, the individuals that do not have "has mode of action" relationships to individuals that are not members of the class "inhibition". - PMCID: PMC3149580

Only or Some can be determine by looking at all the individuals for a certain property

**Comment by chung88** [comment]
file:  s3_BAO new term 8_27

**Comment by chung88** [comment]
label "Partition Coefficient" 
<img width="988" alt="Screen Shot 2023-09-08 at 11 31 39 AM" src="https://github.com/BioAssayOntology/BAO/assets/3586358/72e2c69f-d3b5-4e2e-9afd-97da330a587f">

**Comment by chung88** [comment]
module             id           label                
 -----------------  -----------  -------------------- 
 vocabulary_assay   BAO_0013019  clearance            
 vocabulary_assay   BAO_0013020  CLint                
 vocabulary_format  BAO_0020011  blood format         
 vocabulary_result  BAO_0080048  fraction metabolised
