### ISSUE TITLE
ADME cardinality restrictions "has cell line" 

### ISSUE THREAD

**Issue by chung88** [BioAssayOntology/BAO#68]
"has cell line" = http://www.bioassayontology.org/bao#BAO_0002004 
- 32 records "has cell line"  class-relationship-restriction
- 6 records will not be added
- 3 records found a second cell line
- 5 cell lines are not in BAO #69

**Comment by JoanGlennyPescov** [comment]
what is the exact reason for why this case is open?

**Comment by chung88** [comment]
Changes in BAO v 2.8.1
Curated annotations for ADME set of bioassays cardinality restriction for
•	has cell line (38) (https://github.com/BioAssayOntology/BAO/issues/68)
o	external CLO module
o	29 HEK293 cell line (http://purl.obolibrary.org/obo/CLO_0001230)
o	5 MDCK cell line (http://purl.obolibrary.org/obo/CLO_0007646)
