### ISSUE TITLE
ADME cardinality restrictions "has substrate"

### ISSUE THREAD

**Issue by chung88** [BioAssayOntology/BAO#78]
A bioassay can have some or only a substrate, depending on the assay design.  The substrate is molecule entity, identified in ChEBI, under the assay method component.  
Needs curation [bioassay_AH.txt](https://github.com/BioAssayOntology/BAO/files/11433391/bioassay_AH.txt)

**Comment by JoanGlennyPescov** [comment]
not sure what the issue is on this one?

**Comment by chung88** [comment]
bioassay_BAO_ID |   |  | has_substrate_BAO_ID | ChEBI_ID | restriction
-- | -- | -- | -- | -- | --
BAO_0010191 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_38545 | only
BAO_0010149 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_8050 | some
BAO_0010149 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_3219 | some
BAO_0010149 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_6931 | some
BAO_0010159 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_8050 | some
BAO_0010159 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_179062 | some
BAO_0010159 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_3219 | some
BAO_0010159 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_2674 | some
BAO_0010159 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_47381 | some
BAO_0010159 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_7565 | some
BAO_0010125 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_77780 | some
BAO_0010125 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_165840 | some
BAO_0010125 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_28593 | some
BAO_0010125 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_50730 | some
BAO_0010125 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_45735 | some
BAO_0010170 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_8050 | some
BAO_0010170 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_179062 | some
BAO_0010170 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_3219 | some
BAO_0010170 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_2674 | some
BAO_0010170 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_47381 | some
BAO_0010170 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_4470 | some
BAO_0010170 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_6931 | some
BAO_0010170 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_17347 | some
BAO_0010170 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_7565 | some
BAO_0010171 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_8050 | some
BAO_0010171 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_3219 | some
BAO_0010171 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_2674 | some
BAO_0010171 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_179062 | some
BAO_0010171 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_47381 | some
BAO_0010171 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_4470 | some
BAO_0010171 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_6931 | some
BAO_0010171 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_17347 | some
BAO_0010169 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_8050 | some
BAO_0010169 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_179062 | some
BAO_0010169 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_3219 | some
BAO_0010169 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_2674 | some
BAO_0010169 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_47381 | some
BAO_0010169 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_4470 | some
BAO_0010169 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_6931 | some
BAO_0010169 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_17347 | some
BAO_0010169 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_7565 | some
BAO_0010150 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_8050 | some
BAO_0010160 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_8050 | some
BAO_0010151 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_3219 | some
BAO_0010161 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_3219 | some
BAO_0010163 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_2674 | some
BAO_0010164 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_47381 | some
BAO_0010162 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_179062 | some
BAO_0010155 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_6931 | some
BAO_0010165 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_7565 | some
BAO_0010165 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_6931 | some
BAO_0010165 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_17347 | some
BAO_0010168 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_8050 | some
BAO_0010168 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_3219 | some
BAO_0010168 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_2674 | some
BAO_0010168 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_179062 | some
BAO_0010168 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_47381 | some
BAO_0010168 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_4470 | some
BAO_0010168 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_6931 | some
BAO_0010168 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_17347 | some
BAO_0010168 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_7565 | some
BAO_0010189 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_38545 | some
BAO_0010189 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_6801 | some
BAO_0010189 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_36257 | some
BAO_0010194 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_6801 | some
BAO_0010195 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_6801 | some
BAO_0010158 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_73472 | some
BAO_0010200 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_38545 | some
BAO_0010201 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_38545 | some
BAO_0010202 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_6801 | some
BAO_0010203 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_6801 | some
BAO_0010193 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_36257 | some
BAO_0010188 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_38545 | some
BAO_0010188 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_36257 | some
BAO_0010188 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_6801 | some
BAO_0010173 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_23965 | some
BAO_0010173 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_45951 | some
BAO_0010173 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_44915 | some
BAO_0010173 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_7823 | some
BAO_0010173 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_10110 | some
BAO_0010174 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_23965 | some
BAO_0010175 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_23965 | some
BAO_0010176 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_45951 | some
BAO_0010177 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_45951 | some
BAO_0010180 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_44915 | some
BAO_0010181 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_44915 | some
BAO_0010182 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_7823 | some
BAO_0010183 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_7823 | some
BAO_0010184 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_10110 | some
BAO_0010185 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_10110 | some
BAO_0010196 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_38545 | some
BAO_0010196 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_4873 | some
BAO_0010196 |   |   | BAO_0002739 | http://purl.obolibrary.org/obo/CHEBI_6801 | some
