### ISSUE TITLE
`bao_complete.owl` has unclosed rdfs:comment tag making it unable to be loaded.

### ISSUE THREAD

**Issue by nikogeg** [BioAssayOntology/BAO#86]
Hello! On line 28 in `bao_complete.owl` there is an unclosed rdfs:comment:

https://raw.githubusercontent.com/BioAssayOntology/BAO/master/bao_complete.owl
`	<rdfs:comment>Contact:Stephan Schurer stephan dot schurer at med dot miami dot edu<rdfs:comment>`

This prevents me from loading the data without fixing it manually.

**Comment by chung88** [comment]
![image](https://github.com/BioAssayOntology/BAO/assets/3586358/9f725293-5e89-4a25-abc8-f4e02184d887)
[bao_complete.owl](https://github.com/BioAssayOntology/BAO/blob/master/bao_complete.owl)
[patch update for BAO v2.8.4](https://github.com/BioAssayOntology/BAO/commit/ac6e29586a05b531ccdef47f71904fe16660c894)
