### ISSUE TITLE
update labels

### ISSUE THREAD

**Issue by chung88** [BioAssayOntology/BAO#90]
Update 23 BAO labels

**Comment by chung88** [comment]
Revise relabeling for record number 8 
![image](https://github.com/BioAssayOntology/BAO/assets/3586358/0f263375-2358-4fc6-9c7a-7888020bd37b)


- "hepatocyte relay with inhibitors" http://www.bioassayontology.org/bao#BAO_0010118 is an assay method under bioassay

- http://www.bioassayontology.org/bao#BAO_0000124 is "enzyme activity measurement method" is an assay method

**Comment by JoanGlennyPescov** [comment]
- "hepatocyte relay assay" : parent: "enzyme reaction phenotyping" BAO_0010114

- "hepatocyte relay method" : parent: "enzyme activity measurement method" BAO_0000124

^^
Nicolette and I agreed on it

**Comment by chung88** [comment]
Change	BAO_ID	BAO_label	update_BAO_label
8	BAO_0010170	CYP time dependent inhibition IC50 shift	CYP time dependent inhibition IC50 shift assay
8	BAO_0010171	CYP time dependent inhibition Ki/kinact	CYP time dependent inhibition kinact/KI assay
8	BAO_0010172	CYP time dependent inhibition single point	CYP time dependent inhibition single point assay
8	BAO_0010166	CYP cocktail IC50	CYP cocktail IC50 assay
8	BAO_0010167	CYP single point inhibition	CYP single point inhibition assay
8	BAO_0010142	milk excretion assay	human mammary epithelial cell permeability assay
8	BAO_0010118	hepatocyte relay with inhibitors	hepatocyte relay assay
8	BAO_0010158	monoamine oxidase inhibition	monoamine oxidase inhibition assay
8	BAO_0010126	recombinant CYP reaction phenotyping	recombinant CYP reaction phenotyping assay
8	BAO_0010117	MAO reaction phenotyping	MAO reaction phenotyping assay
8	BAO_0010131	recombinant UGT reaction phenotyping	recombinant UGT reaction phenotyping assay
8	BAO_0010173	UGT inhibition	UGT inhibition assay
8	BAO_0010169	CYP time-dependent inhibition	CYP time-dependent inhibition assay
8	BAO_0010174	UGT1A1 with BSA	UGT1A1 with BSA assay
8	BAO_0010175	UGT1A1 without BSA	UGT1A1 without BSA assay
8	BAO_0010176	UGT1A4 with BSA	UGT1A4 with BSA assay
8	BAO_0010177	UGT1A4 without BSA	UGT1A4 without BSA assay
8	BAO_0010180	UGT1A9 with BSA	UGT1A9 with BSA assay
8	BAO_0010181	UGT1A9 without BSA	UGT1A9 without BSA assay
8	BAO_0010182	UGT2B15 with BSA	UGT2B15 with BSA assay
8	BAO_0010183	UGT2B15 without BSA	UGT2B15 without BSA assay
8	BAO_0010184	UGT2B7 with BSA	UGT2B7 with BSA assay
8	BAO_0010185	UGT2B7 without BSA	UGT2B7 without BSA assay
